/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_appuninstalldemo_MainActivity */

#ifndef _com_ciyun_lovehealth_HealthApplication
#define _com_ciyun_lovehealth_HealthApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_appuninstalldemo_MainActivity
 * Method:    uninstall
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ciyun_lovehealth_HealthApplication_uninstall
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
